### ISSUE TITLE
INTERNATIONAL NODESCHOOL DAY

### ISSUE THREAD

**Issue by diasdavid** [nodeschool/lisbon#1]
YES! :D 
@sericaia

**Comment by joaojeronimo** [comment]
let's do it!

**Comment by danielaborges** [comment]
I am totally interested to organize this event :dancer: 
Anyone wants to join the 'team'?

More about the event:
http://nodeschool.io/international-day/
https://github.com/nodeschool/international-day/issues/8

**Comment by iancrowther** [comment]
+1

**Comment by pmvrmc** [comment]
If you need an extra pair of hands count me in!

**Comment by sericaia** [comment]
Added! https://github.com/nodeschool/international-day/issues/8#issuecomment-83164133

**Comment by diasdavid** [comment]
woot! :D

**Comment by joaquimserafim** [comment]
:+1:

**Comment by foliveira** [comment]
:+1: Count me in!

**Comment by joaquimserafim** [comment]
wow free kebab :P

**Comment by diasdavid** [comment]
http://www.meetup.com/require-lx/events/221544407/

**Comment by foliveira** [comment]
And awesome new logo

 ![](https://raw.githubusercontent.com/nodeschool/lisbon/master/logos/NodeSchool%20LX%20B.png)

to go with

![](https://raw.githubusercontent.com/nodeschool/international-day/2015/assets/logo.png)

**Comment by sericaia** [comment]
cool! :dancer:
